"""empty message

Revision ID: e70469e1a57f
Revises: 6e7bd0d31457
Create Date: 2019-10-09 09:23:52.955181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70469e1a57f'
down_revision = '6e7bd0d31457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('list__id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todoList', ['list__id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list__id')
    op.drop_table('todoList')
    # ### end Alembic commands ###
